### ISSUE TITLE
Error command mlvm list on Mac OS X 10.10.1

### ISSUE THREAD

**Issue by maachou** [withjam/mlvm#18]
Hi, I just installed mlvm on Mac OS X Yosemite 10.10.1. After executing the command **mlvm list** I get the following error:
```batch
$ mlvm list
Installed MarkLogic Versions:
usage: dirname path
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
/Users/mmaachou/Dev/Tools/mlvm/mlvm.sh: line 121: [: =: unary operator expected
```

**Comment by damonfeldman** [comment]
I get this too. Any resolution appreciated.

**Comment by jmakeig** [comment]
From where you ran the `mlvm` command, what does `ls -laGh versions/` return?
