### ISSUE TITLE
No files found

### ISSUE THREAD

**Issue by clockworked247** [withjam/mlvm#22]
Failure occurs when attempting to mount 8.0.1-1 with an absolute path to 8.0-1.1:

mlvm install 8.0-1.1 /Users/sbrooks/Desktop/mlvm/MarkLogic-8.0-1.1-x86_64.dmg 
8.0-1.1
/Users/sbrooks/Desktop/mlvm/MarkLogic-8.0-1.1-x86_64.dmg
Mounting 8.0.1-1 to /Users/sbrooks/Desktop/mlvm/.mounts/142561981421724
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
total 0
drwxr-xr-x  2 sbrooks  1258547899   68 Mar  5 21:30 .
drwxrwxrwx  4 sbrooks  1258547899  136 Mar  5 21:30 ..
No files found, exiting

-----

.bash_profile
------------------
alias mlvm="~/Desktop/mlvm/mlvm.sh"
alias sudo='sudo '

mlvm prepare output
------------------------------
Did not detect an existing install of MarkLogic
ln: /Users/sbrooks/Library/StartupItems/MarkLogic: No such file or directory
Ready to manage MarkLogic versions with mlvm.
Use 'mlvm list' to see installed versions
Use 'mlvm install <dmg_file> [<version_name>]' to install a version
Use 'mlvm use <version_name>' to switch to an installed version
Use 'mlvm remove <version_name>' to remove an installed version (not recoverable)

(which is correct - there is no ML installed via an installer)

**Comment by clockworked247** [comment]
After walking through this with the team, we figured out that the issue was that a Marklogic was already mounted (maybe from a previous failed attempt).  Once I ejected it and ran the script again, everything worked great.

**Comment by popzip** [comment]
Just ran into this...had to manually eject previously mounted instances from finder...not sure how i ended up here but was glad to find this thread.
